[package]
name = "clock"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

[dependencies]
chain-time           = { path = "../../chain-deps/chain-time"}
tokio = { version = "0.2.22", default-features = false, features = ["time"] }